PREFIX evs: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oio: <http://www.geneontology.org/formats/oboInOwl#>

DELETE {
  ?s ?p ?old_property .
}
INSERT {
  ?s ?p ?new_property .
}
WHERE {
  VALUES (?old_property ?new_property) {
    (evs:P97 obo:IAO_0000115)
    (evs:P90 oio:hasExactSynonym)
    (evs:A8  oio:inSubset)
  }
  ?s ?p ?old_property .
}
