DELETE {
    <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl> ?p ?o .
}
INSERT {
  <http://purl.obolibrary.org/obo/ncit.owl> ?p ?o .
}
WHERE {
  <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl> ?p ?o .
}
